version: '3.8'

services:
  app:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432



